// <auto-generated />
using System;
using LizardCorpBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LizardCorpBot.Data.Migrations
{
    [DbContext(typeof(LizardBotDbContext))]
    [Migration("20240129130215_20240129_5")]
    partial class _20240129_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LizardCorpBot.Data.Model.Guild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("GuildId");

                    b.ToTable("guild");
                });

            modelBuilder.Entity("LizardCorpBot.Data.Model.GuildUser", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("guild_user");
                });

            modelBuilder.Entity("LizardCorpBot.Data.Model.MinecraftUser", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("boolean")
                        .HasColumnName("is_playing");

                    b.Property<DateTime?>("LastJoined")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_joined");

                    b.Property<long>("PlayTime")
                        .HasColumnType("bigint")
                        .HasColumnName("playtime");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Name");

                    b.ToTable("minecraft_user");
                });

            modelBuilder.Entity("LizardCorpBot.Data.Model.TodoChannel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.HasKey("GuildId");

                    b.ToTable("todo_channel");
                });
#pragma warning restore 612, 618
        }
    }
}
